#include QMK_KEYBOARD_H
#include "ratoru.h"
#include "features/select_word.h"
#include "features/layer_lock.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_UNDS, KC_ESC, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, RGUI_T(KC_QUOT), OSM(MOD_LSFT), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LCTL, CW_TOGG, QK_AREP, QK_REP, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, OSM(MOD_RSFT), KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, MO(1), LT(3,KC_ENT), LT(2,KC_SPC), LGUI_T(KC_BSPC), SELWORD, TO(4)),
	[1] = LAYOUT(KC_TAB, LGUI(KC_Q), LGUI(KC_W), LGUI(KC_BSLS), LGUI(KC_R), LGUI(KC_T), KC_VOLU, LCA(KC_TAB), KC_UP, LCTL(KC_TAB), KC_DEL, KC_TRNS, KC_ESC, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_TRNS, KC_VOLD, KC_LEFT, KC_DOWN, KC_RGHT, KC_BSPC, KC_ENT, KC_LSFT, LGUI(KC_Z), LGUI(KC_X), LGUI(KC_C), LGUI(KC_V), KC_TRNS, LLOCK, KC_SCRL, KC_TRNS, KC_TRNS, KC_MUTE, KC_MPRV, KC_MPLY, KC_MNXT, KC_BRID, KC_BRIU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[2] = LAYOUT(KC_TRNS, KC_TILD, KC_LT, KC_GT, KC_HASH, KC_AT, KC_AMPR, KC_COLN, KC_LBRC, KC_RBRC, KC_BSLS, KC_TRNS, KC_TRNS, KC_EXLM, KC_MINS, KC_PLUS, KC_EQL, KC_GRV, KC_DLR, KC_UNDS, KC_LPRN, KC_RPRN, KC_PERC, KC_TRNS, KC_TRNS, KC_CIRC, KC_SLSH, KC_ASTR, KC_0, UPDIR, LLOCK, KC_TRNS, KC_TRNS, KC_TRNS, KC_PIPE, KC_1, KC_LCBR, KC_RCBR, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT(KC_TRNS, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS, KC_MINS, KC_7, KC_8, KC_9, KC_PLUS, KC_TRNS, KC_TRNS, KC_F5, KC_F6, KC_F7, KC_F8, KC_TRNS, KC_ASTR, KC_4, KC_5, KC_6, KC_0, KC_TRNS, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_TRNS, LLOCK, KC_TRNS, KC_TRNS, KC_TRNS, KC_SLSH, KC_1, KC_2, KC_3, KC_EQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[4] = LAYOUT(KC_TAB, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_LGUI, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RSFT, KC_Z, KC_X, KC_C, KC_SPC, KC_V, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TO(0))
};

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
  if (!process_select_word(keycode, record, SELWORD)) { return false; }
  if (!process_layer_lock(keycode, record, LLOCK)) { return false; }

  switch (keycode) {
    case UPDIR:  // Types ../ to go up a directory on the shell.
      if (record->event.pressed) {
        SEND_STRING("../");
      }
      return false;
  }
  return true;
}
